apiVersion: v1
kind: ConfigMap

metadata:
  name: redis-configmap

data:
  redis.conf:  |+
    # cluster configs
    cluster-enabled yes
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    # volume configs
    appendonly yes
    protected-mode no
    dir /data
    # port configs
    port 6379;