apiVersion: v1
kind: PersistentVolume

metadata:
  name: local-pv1

spec:
  storageClassName: crypto-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"