apiVersion: v1
kind: ConfigMap

metadata:
  name: cryptometer-configmap

data:
  config.yml:  |+
    port: 6030
    crypto:
      name: "bitcoin"
      value: "usd"
    storage:
      host: "redis:6037"
      password: ""
      timeout: 5