apiVersion: v1
kind: ConfigMap

metadata:
  name: cryptometer-configmap

data:
  config.yml:  |+
    port: 6030
    crypto:
      name: "bitcoin"
      value: "usd"
    storage:
      host: "10.96.76.80:6037"
      password: "12345678"
      timeout: 5
