apiVersion: apps/v1
kind: Deployment

metadata:
  name: cryptometer

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptometer
  template:
    spec:
      containers:
        - name: cryptometer
          image: amirhossein21/cryptometer:v0.1
          ports:
            - containerPort: 6030
              name: cryptometer
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: configmap
            items:
            - key: cryptometer-configmap
              path: config.yml
